### ISSUE TITLE
broken link to BBOB-2009 comparison

### ISSUE THREAD

**Issue by pierre-haessig** [CMA-ES/CMA-ES.github.io#2]
Hello,
On the main CMA-ES webpage https://cma-es.github.io/index.html, there are two links to he BBOB 2009 comparison with URL https://numbbo.github.io/ppdata-archive/bbob/2009-all. This yields a "404 Page not found" error. I don't know if its  correct, but https://numbbo.github.io/ppdata-archive/bbob/2009/index.html at least returns "something reasonable".

**Comment by nikohansen** [comment]
Thanks! I just fixed the links.
